version: "3.9"

services:
  db:
    image: postgres:16
    container_name: notes-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notes
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: notes-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://neondb_owner:npg_e2trEBRs7gTA@ep-holy-poetry-adkliqlc-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require

      SECRET_KEY: supersecret123
    ports:
      - "8001:8000"

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
